Feature/sign up base
todaynan/Android pull request #7
Opened 2024-07-20 11:18 UTC by bulee5328

## 관련 화면 및 연관된 이슈
- 화면: 회원가입 및 관련 설문
- 이슈: 회원가입 화면 구성, 이동

## 요약
어떠한 기능을 개발했는지 간단하게 요약해주세요

## 완료사항
1. 회원가입 화면 구성, 이동 구현 
2. 회원가입 화면 중 선택지 선택 시 완료 버튼 연결

## 미완료사항
1. SNS 로그인 관련부분
2. 주로 이렇게 놀아요! - 텍스트 정보 반영
3. 마이펫 중복 방지

2024-07-20 12:01 UTC, jerry080697 commented
확인했습니다

2024-07-20 12:02 UTC, jerry080697 approved these changes
확인했습니다

2024-07-21 13:14 UTC, thwldus approved these changes
Page2SignUP.kt에서 각 기능을 함수로 나누어 구현하신 것 같네요!
수고하셨습니다

2024-07-21 13:17 UTC, thwldus requested changes
Activity 관련 파일 이름 확인 부탁드립니다

2024-07-21 13:17 UTC, thwldus commented on app/src/main/AndroidManifest.xml
> +        <activity android:name=".Page8SignUp"/>
Page관련 Activity도 이름을 '~Activity' 형식으로 맞추면 좋을 것 같습니다.

2024-07-22 05:21 UTC, merged